imports:
    - { resource: base_config.yml }
    - { resource: parameters.yml }

parameters:
    fork.is_installed: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@simple_bus.command_bus' # Generic // This should be replaced with the Messenger component
            $siteIsMultiLingual: '%site.multilanguage%' # Pages
            $rootDir: '%kernel.project_dir%/' # RequirementsChecker
            $projectDirectory: '%kernel.project_dir%' # InstallCommand
            $forkIsInstalled: '%fork.is_installed%' # InstallCommand
            $sitePath: '%site.path_www%' # Thumbnails

    ForkCMS\:
        resource: '../../src/ForkCMS/*'
        exclude:
            - '../../src/ForkCMS/**/*Test.php'
    Backend\:
        resource: '../../src/Backend/*'
        exclude:
            - '../../src/Backend/Form/EventListener/AddMetaSubscriber.php'
            - '../../src/Backend/**/*Test.php'
    Frontend\:
        resource: '../../src/Frontend/*'
        exclude:
            - '../../src/Frontend/**/*Test.php'
    Common\:
        resource: '../../src/Common/*'
        exclude:
            - '../../src/Common/**/*Test.php'

    ForkCMS\App\ForkController:
    Common\Core\Cookie:
        public: true
    Common\ModulesSettings:
        public: true
    ForkCMS\Utility\Module\CopyContentToOtherLocale\CopyContentFromModulesToOtherLocaleManager:
        public: true
    SpoonDatabase:
        class: SpoonDatabase
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%"
            - "%database.port%"
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
            # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
            # and caused some queries to break.
            - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")'] ]
            - [ setDebug, [ "%kernel.debug%" ]]

#    templating:
#        class: Frontend\Core\Engine\TwigTemplate
#        public: true
#        arguments:
#            - "@twig"
#            - "@templating.name_parser"
#            - "@templating.locator"
#
#    translator:
#        class: Common\Language
#        public: true
