imports:
    - { resource: base_config.yml }
    - { resource: parameters_install.yml }

parameters:
    doctrine.dbal.connection_factory.class: ForkCMS\Bundle\InstallerBundle\Service\InstallerConnectionFactory
    fork.is_installed: false
    fork.form.theme: "ForkCMSInstallerBundle:Installer:form_theme.html.twig"

twig: ~

framework:
    secret: "%kernel.secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing_install.yml"

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ 'ForkCMSInstallerBundle' ]
#    filters:
#        cssrewrite: ~

monolog:
    handlers:
        main:
            type: stream
            path: "%site.path_www%/var/logs/%kernel.environment%/debug.log"
            level: debug

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@simple_bus.command_bus' # Generic // This should be replaced with the Messenger component
            $siteIsMultiLingual: '%site.multilanguage%' # Pages
            $rootDir: '%kernel.project_dir%/' # RequirementsChecker
            $projectDirectory: '%kernel.project_dir%' # InstallCommand
            $forkIsInstalled: '%fork.is_installed%' # InstallCommand
            $sitePath: '%site.path_www%' # Thumbnails

    ForkCMS\:
        resource: '../../src/ForkCMS/*'
        exclude:
            - '../../src/ForkCMS/**/*Test.php'
    Backend\:
        resource: '../../src/Backend/*'
        exclude:
            - '../../src/Backend/Form/EventListener/AddMetaSubscriber.php'
            - '../../src/Backend/**/*Test.php'
    Frontend\:
        resource: '../../src/Frontend/*'
        exclude:
            - '../../src/Frontend/**/*Test.php'
    Common\:
        resource: '../../src/Common/*'
        exclude:
            - '../../src/Common/**/*Test.php'

    ForkCMS\Bundle\InstallerBundle\Controller\InstallerController:
    ForkCMS\App\ForkController:
    Common\Core\Cookie:
        public: true
    Common\ModulesSettings:
        public: true
    ForkCMS\Utility\Module\CopyContentToOtherLocale\CopyContentFromModulesToOtherLocaleManager:
        public: true
    Backend\Modules\Locale\Engine\CacheBuilder:
        public: true
    Backend\Modules\Pages\Engine\CacheBuilder:
        public: true
    Backend\Modules\Pages\Domain\Page\PageRepository:
        public: true
    Frontend\Core\Engine\TwigTemplate:
        public: true
        arguments:
            - "@twig.loader"
    ForkCMS\Bundle\CoreBundle\Validator\UrlValidator:
        public: true
    Common\BlockEditor\Twig\ParseBlocksExtension:
        public: true
    Common\Doctrine\Entity\CreateSchema:
        public: true
    Monolog\Logger:
        arguments:
            - 'app'
        public: true
    SpoonDatabase:
        class: SpoonDatabase
        public: true
        arguments:
            - "%env(resolve:SPOON_DATABASE_DRIVER)%"
            - "%env(resolve:SPOON_DATABASE_HOST)%"
            - "%env(resolve:SPOON_DATABASE_USER)%"
            - "%env(resolve:SPOON_DATABASE_PASSWORD)%"
            - "%env(resolve:SPOON_DATABASE_NAME)%"
            - "%env(resolve:SPOON_DATABASE_PORT)%"
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
            # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
            # and caused some queries to break.
            - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")'] ]
            - [ setDebug, [ "%kernel.debug%" ]]

#services:
#    templating:
#        alias: templating.engine.twig
#
#    fork.settings:
#        class: Common\ModulesSettings
#        public: true
#        arguments:
#            - "@database"
#            - "@cache.pool"
#            - "%fork.is_installed%"
#
#    # dummy service during the installation
#    mailer_configurator:
#        class: stdClass
#
#    cache.pool:
#        class: Symfony\Component\Cache\Adapter\ArrayAdapter
#
#    database:
#        class: SpoonDatabase
#        public: true
#        arguments:
#            - "%database.driver%"
#            - "%database.host%"
#            - "%database.user%"
#            - "%database.password%"
#            - "%database.name%"
#            - "%database.port%"
#        calls:
#            - [ setDebug, [ "%kernel.debug%" ]]

# Doctrine Configuration
doctrine:
    dbal:
        types:
            locale: ForkCMS\Bundle\InstallerBundle\DBALType\LocaleDBALType
